### ISSUE TITLE
Ability/flexibility for more software engineering quotes

### ISSUE THREAD

**Issue by weblancaster** [daviferreira/github-zen-chrome#2]
Hey @daviferreira I was thinking instead of use Github zen why not include in the repo `quotes.json` and there populate with software engineering quotes and contributors send PR quotes?

e.g:
http://www.comp.nus.edu.sg/~damithch/pages/SE-quotes.htm
http://www.multicians.org/thvv/proverbs.html
http://cseweb.ucsd.edu/~wgg/quotes.html
http://www.goodreads.com/quotes/tag/software-engineering

Why?
Github Zen code has a very low number of quotes.

Let me know what you think.

**Comment by daviferreira** [comment]
Hey man, then maybe I think it's better to create a new extension. This one I would like to keep with github zen quotes only :smile:
